/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.form;

import com.mycompany.model.Account;
import com.mycompany.model.StatusType;
import com.mycompany.qlnt.SharedData;
import com.mycompany.swing.scrollbar.ModernScrollBarUI;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quang
 */
public class DienNuocForm extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public DienNuocForm() {
        initComponents();
        laydstro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listNhaTro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        listphongtro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diencu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dienmoi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dienmoii = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        diencuu = new javax.swing.JLabel();
        dm = new javax.swing.JLabel();
        dtt = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nuoccu = new javax.swing.JLabel();
        nuocmoi = new javax.swing.JLabel();
        ntt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nhapnuoc = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("TÍNH SỐ ĐIỆN & NƯỚC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Tên Nhà Trọ");

        listNhaTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listNhaTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listNhaTroActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Phòng Trọ");

        listphongtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listphongtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listphongtroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tiền điện");

        jLabel6.setText("Số điện cũ");

        jLabel8.setText("Số điện mới");

        dienmoi.setText("Nhập tiền điện mới");
        dienmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dienmoiActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Số điện tiêu thụ");

        diencuu.setText("diencu");

        dm.setText("dienmoii");

        dtt.setText("jLabel12");

        jLabel13.setText("Cập nhập số điện");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tiền nước");

        jLabel11.setText("Số nước cũ");

        jLabel12.setText("Số nước mới");

        jLabel14.setText("Số nước tiêu thụ");

        nuoccu.setText("nuoccu");

        nuocmoi.setText("nuocmoi");

        ntt.setText("jLabel17");

        jLabel15.setText("Cập nhập số nước");

        nhapnuoc.setText("Nhập số nước mới");
        nhapnuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapnuocActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(listphongtro, javax.swing.GroupLayout.Alignment.LEADING, 0, 167, Short.MAX_VALUE)
                                .addComponent(listNhaTro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(diencu)
                                .addGap(27, 27, 27)
                                .addComponent(diencuu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(191, 191, 191))
                            .addComponent(dienmoii, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dtt)
                                            .addComponent(dm)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(dienmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(248, 248, 248)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ntt)
                                            .addComponent(nuocmoi)
                                            .addComponent(nuoccu)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(nhapnuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2)))))))
                        .addContainerGap(222, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(listphongtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(diencu)
                    .addComponent(diencuu)
                    .addComponent(jLabel11)
                    .addComponent(nuoccu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dienmoii)
                    .addComponent(dm)
                    .addComponent(jLabel12)
                    .addComponent(nuocmoi))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dtt)
                    .addComponent(jLabel14)
                    .addComponent(ntt))
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dienmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel15)
                    .addComponent(nhapnuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
public static boolean isFloat(String str) {
        try {
            Float.parseFloat(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float k = Float.parseFloat(dm.getText());
        float m=Float.parseFloat(dienmoi.getText());
        if(isFloat(dienmoi.getText())==true && k<m)
        {

           String selectedPhong = (String) listphongtro.getSelectedItem();
        String newValue = dienmoi.getText();

        String getIdDienSql = "SELECT p.idDien " +
                              "FROM phong AS p " +
                              "WHERE p.tenPhong = ?";
        String updateSqll = "UPDATE ElectricMeter SET oldValue = ? WHERE idDien = ?";
        String updateSql = "UPDATE ElectricMeter SET Value = ? WHERE idDien = ?";

        try (Connection con = ketNoiDB.ketNoiDB.layKetNoi();
             PreparedStatement getIdDienPs = con.prepareStatement(getIdDienSql);
             PreparedStatement updatePss = con.prepareStatement(updateSqll);
             PreparedStatement updatePs = con.prepareStatement(updateSql)) {
            
            // Lấy idDien từ tenPhong
            getIdDienPs.setString(1, selectedPhong);
            ResultSet rs = getIdDienPs.executeQuery();

            String idDienn="";
            if (rs.next()) {
                idDienn = rs.getString("idDien");
            }
            rs.close();
            
            // Cập nhật giá trị mới vào cột Value
            updatePss.setString(1,SharedData.getInstance().getTd() );
                updatePss.setString(2, idDienn);
                updatePss.executeUpdate();
                updatePs.setString(1, newValue);
                updatePs.setString(2, idDienn);
                updatePs.executeUpdate();
                updatePss.close();
        } catch (SQLException exSQL) {
        }
    layttd(SharedData.getInstance().getIdp());

        }
        else {
             JOptionPane.showMessageDialog(null," Phải là một số và số nhập phải lớn hơn số cũ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Xóa nội dung không hợp lệ từ textField
            dienmoi.setText("");
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dienmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dienmoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dienmoiActionPerformed

    private void listphongtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listphongtroActionPerformed
        // TODO add your handling code here:
        String a = (String) listphongtro.getSelectedItem();
        layttd(a);
        layttn(a);
        SharedData.getInstance().setIdp(a);
    }//GEN-LAST:event_listphongtroActionPerformed

    public void layttd(String a){
        Connection con = ketNoiDB.ketNoiDB.layKetNoi();
        String selectSql = "SELECT p.tenPhong, d.oldValue, d.Value " +
        "FROM phong AS p " +
        "JOIN ElectricMeter AS d ON p.idDien = d.idDien " +
        "WHERE p.tenPhong = ?";
        

        try {
            // Truy vấn giá trị hiện tại
            PreparedStatement selectPs = con.prepareStatement(selectSql);
            selectPs.setString(1, a);
            ResultSet rs = selectPs.executeQuery();

            String dc = null;

            if (rs.next()) {
                dc = rs.getString("oldValue");
                diencuu.setText(dc);
                String dmm = rs.getString("Value");
                dm.setText(dmm);
                SharedData.getInstance().setTd(dmm);
                float x=Float.parseFloat(diencuu.getText());
                float y=Float.parseFloat(dm.getText());
                float c=y-x;
                dtt.setText(String.valueOf(c));
            }
            rs.close();
            selectPs.close();
            con.close();
        } catch (SQLException exSQL) {
        }
    }
    public void layttn(String a){
        Connection con = ketNoiDB.ketNoiDB.layKetNoi();
        String selectSql = "SELECT p.tenPhong, d.oldValue, d.Value " +
        "FROM phong AS p " +
        "JOIN WaterMeter AS d ON p.idNuoc = d.idNuoc " +
        "WHERE p.tenPhong = ?";
        

        try {
            // Truy vấn giá trị hiện tại
            PreparedStatement selectPs = con.prepareStatement(selectSql);
            selectPs.setString(1, a);
            ResultSet rs = selectPs.executeQuery();

            String nc = null;

            if (rs.next()) {
                nc = rs.getString("oldValue");
                nuoccu.setText(nc);
                String ncc = rs.getString("Value");
                nuocmoi.setText(ncc);
                SharedData.getInstance().setTn(ncc);
                float x=Float.parseFloat(nuoccu.getText());
                float y=Float.parseFloat(nuocmoi.getText());
                float c=y-x;
                ntt.setText(String.valueOf(c));
            }
            rs.close();
            selectPs.close();
            con.close();
        } catch (SQLException exSQL) {
        }
    }
    
    private void listNhaTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listNhaTroActionPerformed
        // TODO add your handling code here:
        String a = (String) listNhaTro.getSelectedItem();
        String sql = "SELECT NhaTro.idNhaTro FROM NhaTro WHERE tenNhaTro=?";

        String query = "SELECT nt.idNhaTro, nt.tenNhaTro, lp.idLoaiPhong, lp.tenLoaiPhong, p.idPhong, p.tenPhong " +
        "FROM NhaTro AS nt " +
        "JOIN LoaiPhong AS lp ON nt.idNhaTro = lp.idNhaTro " +
        "JOIN Phong AS p ON lp.idLoaiPhong = p.idLoaiPhong " +
        "WHERE nt.idNhaTro = ?";

        try (Connection con = ketNoiDB.ketNoiDB.layKetNoi();
            PreparedStatement pss = con.prepareStatement(sql)) {

            pss.setString(1, a);

            String b = null;
            try (ResultSet rss = pss.executeQuery()) {
                if (rss.next()) {
                    b = rss.getString("idNhaTro");
                }
            }

            if (b != null) {
                try (PreparedStatement ps = con.prepareStatement(query)) {
                    ps.setString(1, b);

                    try (ResultSet rs = ps.executeQuery()) {
                        listphongtro.removeAllItems(); // Xóa tất cả các mục hiện tại trong listphongtro

                        while (rs.next()) {
                            String tenpt = rs.getString("tenPhong");
                            listphongtro.addItem(tenpt); // Thêm các mục mới vào listphongtro
                        }
                    }
                }
            }
        } catch (SQLException exSQL) {
        }

    }//GEN-LAST:event_listNhaTroActionPerformed

    private void nhapnuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapnuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapnuocActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float k = Float.parseFloat(nuocmoi.getText());
        float m=Float.parseFloat(nhapnuoc.getText());
        if(isFloat(nhapnuoc.getText())==true && k<m)
        {

           String selectedPhong = (String) listphongtro.getSelectedItem();
        String newValue = nhapnuoc.getText();

        String getIdNuocSql = "SELECT p.idNuoc " +
                              "FROM phong AS p " +
                              "WHERE p.tenPhong = ?";
        String updateSqll = "UPDATE WaterMeter SET oldValue = ? WHERE idNuoc = ?";
        String updateSql = "UPDATE WaterMeter SET Value = ? WHERE idNuoc = ?";

        try (Connection con = ketNoiDB.ketNoiDB.layKetNoi();
             PreparedStatement getIdNuocPs = con.prepareStatement(getIdNuocSql);
             PreparedStatement updatePss = con.prepareStatement(updateSqll);
             PreparedStatement updatePs = con.prepareStatement(updateSql)) {
            
            // Lấy idDien từ tenPhong
            getIdNuocPs.setString(1, selectedPhong);
            ResultSet rs = getIdNuocPs.executeQuery();

            String idNuocc="";
            if (rs.next()) {
                idNuocc = rs.getString("idNuoc");
            }
            rs.close();
            
            // Cập nhật giá trị mới vào cột Value
            updatePss.setString(1,SharedData.getInstance().getTd() );
                updatePss.setString(2, idNuocc);
                updatePss.executeUpdate();
                updatePs.setString(1, newValue);
                updatePs.setString(2, idNuocc);
                updatePs.executeUpdate();
                updatePss.close();
        } catch (SQLException exSQL) {
        }
    layttn(SharedData.getInstance().getIdp());

        }
        else {
             JOptionPane.showMessageDialog(null," Phải là một số và số nhập phải lớn hơn số cũ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            // Xóa nội dung không hợp lệ từ textField
            nhapnuoc.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    protected void paintChildren(Graphics grphcs){
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
        g2.fillRect(getWidth(),0,getWidth(),getHeight());
        super.paintChildren(grphcs);
    }
    public void laydstro(){
        listNhaTro.removeAllItems();
        Connection con = ketNoiDB.ketNoiDB.layKetNoi();
        String sql = "SELECT NhaTro.idNhaTro, NhaTro.tenNhaTro,NhaTro.idQL " +
            "FROM NhaTro " ;
        try{
            
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                String tennt=rs.getString("tenNhaTro");
                String id=rs.getString("idNhaTro");
                listNhaTro.addItem(tennt);
            }
            rs.close();
            ps.close();
            con.close();
        } catch (SQLException exSQL) {
            Logger.getLogger(sql);
        }
    }
    public void laytiendien() {
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diencu;
    private javax.swing.JLabel diencuu;
    private javax.swing.JTextField dienmoi;
    private javax.swing.JLabel dienmoii;
    private javax.swing.JLabel dm;
    private javax.swing.JLabel dtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> listNhaTro;
    private javax.swing.JComboBox<String> listphongtro;
    private javax.swing.JTextField nhapnuoc;
    private javax.swing.JLabel ntt;
    private javax.swing.JLabel nuoccu;
    private javax.swing.JLabel nuocmoi;
    // End of variables declaration//GEN-END:variables
}
